/** Golden parity suite — the port-fidelity contract (PLAN.md Phase 2.3).
 *
 *  Golden values are generated by EXECUTING mockup/engine.js (pure, dependency-free
 *  ESM) in the same test run — never hand-computed. If any frozen constant or subtle
 *  behavior drifts in the port, these fail loudly. The interim transitions JSON is
 *  also transitively verified here: if it deviated from the demo STATS table, every
 *  suggest comparison would diverge.
 */
import { describe, expect, it } from 'vitest'
// @ts-ignore — Phase A reference engine, intentionally untyped (immutable mockup reference)
import * as demo from '../../mockup/engine.js'
import { makeKey, type Chord, type Key } from '../theory/chords.ts'
import { parseName } from '../theory/chords.ts'
import { parseRoman } from '../theory/roman.ts'
import { voice } from '../theory/voicing.ts'
import { candidates } from './rules.ts'
import { suggest, type Suggestion } from './blend.ts'
import { conjure } from './conjure.ts'
import { chips } from './chips.ts'
import { demoStats, mulberry32 } from '../test/helpers.ts'

/* eslint-disable @typescript-eslint/no-explicit-any */
type DemoChord = Record<string, any>

const KEYS: Array<[string, 'minor' | 'major']> = [
  ['A', 'minor'], ['C', 'major'], ['E', 'minor'], ['B♭', 'major'], ['F♯', 'minor'],
]
const DIALS = [0, 20, 38, 50, 60, 75, 90, 100]

/** Fields shared by both engines' chords (ours adds root/extensions/reason on top). */
function core(ch: DemoChord) {
  return {
    semis: ch.semis, quality: ch.quality, roman: ch.roman, lo: ch.lo,
    func: ch.func, spice: ch.spice, statsId: ch.statsId,
    ints: [...ch.ints], name: ch.name, rootPc: ch.rootPc,
  }
}

function expectSuggestionParity(ours: Suggestion[], theirs: DemoChord[]) {
  expect(ours.length).toBe(theirs.length)
  ours.forEach((s, i) => {
    const d = theirs[i]!
    expect(core(s)).toEqual(core(d))
    expect(s.rank).toBe(d.rank)
    expect(s.score).toBeCloseTo(d.score, 12)
    expect(s.rel).toBeCloseTo(d.rel, 12)
  })
}

describe('golden parity: suggest', () => {
  for (const [root, mode] of KEYS) {
    it(`matches the demo engine in ${root} ${mode} across dials and decks`, () => {
      const key: Key = makeKey(root, mode)
      const dKey = demo.makeKey(root, mode)
      for (const dial of DIALS) {
        // decks built in lockstep: append by rank index so both sides stay equivalent
        let ourDeck: Chord[] = []
        let demoDeck: DemoChord[] = []
        for (const pickRank of [0, 1, 0, 2, 0]) {
          const ours = suggest(demoStats, ourDeck, key, dial)
          const theirs = demo.suggest(demoDeck, dKey, dial)
          expectSuggestionParity(ours, theirs)
          const ours12 = suggest(demoStats, ourDeck, key, dial, 12)
          const theirs12 = demo.suggest(demoDeck, dKey, dial, 12)
          expectSuggestionParity(ours12, theirs12)
          ourDeck = [...ourDeck, ours[pickRank]!]
          demoDeck = [...demoDeck, theirs[pickRank]]
        }
      }
    })
  }

  it('matches the demo engine with the VL tiebreaker armed (prevUppers)', () => {
    const key = makeKey('A', 'minor')
    const dKey = demo.makeKey('A', 'minor')
    const ourDeck = [candidates(key)[0]!]
    const demoDeck = [demo.candidates(dKey)[0]]
    const prev = voice(ourDeck[0]!).uppers
    const dPrev = demo.voice(demoDeck[0]).uppers
    expect(prev).toEqual(dPrev)
    for (const dial of DIALS) {
      expectSuggestionParity(
        suggest(demoStats, ourDeck, key, dial, 6, prev),
        demo.suggest(demoDeck, dKey, dial, 6, dPrev),
      )
    }
  })
})

describe('golden parity: voice', () => {
  for (const [root, mode] of [['A', 'minor'], ['C', 'major']] as const) {
    it(`voices every ${root} ${mode} candidate identically (fresh + chained)`, () => {
      const key = makeKey(root, mode)
      const dKey = demo.makeKey(root, mode)
      const ours = candidates(key)
      const theirs: DemoChord[] = demo.candidates(dKey)
      let prev: number[] | null = null
      let dPrev: number[] | null = null
      ours.forEach((ch, i) => {
        const v = voice(ch, prev)
        const dv = demo.voice(theirs[i], dPrev)
        expect({ bass: v.bass, uppers: v.uppers, all: v.all }).toEqual({ bass: dv.bass, uppers: dv.uppers, all: dv.all })
        expect(v.dist).toBeCloseTo(dv.dist, 12)
        prev = v.uppers
        dPrev = dv.uppers
      })
    })
  }
})

describe('golden parity: conjure', () => {
  for (const [root, mode] of [['A', 'minor'], ['C', 'major']] as const) {
    it(`samples identical progressions in ${root} ${mode} under a shared seeded rng`, () => {
      const key = makeKey(root, mode)
      const dKey = demo.makeKey(root, mode)
      for (const dial of [0, 38, 70, 100]) {
        for (let seed = 1; seed <= 40; seed++) {
          const ours = conjure(demoStats, key, dial, mulberry32(seed))
          const theirs: DemoChord[] = demo.conjure(dKey, dial, mulberry32(seed))
          expect(ours.map(c => c.roman)).toEqual(theirs.map(c => c.roman))
          expect(ours.map(c => c.name)).toEqual(theirs.map(c => c.name))
          // scores are VL-sensitive where romans are not: exact score parity is the
          // direct assertion that conjure never arms the VL tiebreak (PLAN 2.3)
          ours.forEach((c, i) => expect(c.score).toBeCloseTo(theirs[i]!.score, 12))
        }
      }
    })
  }
})

describe('golden parity: chips', () => {
  it('matches the demo pool and filtering in both notations', () => {
    for (const [root, mode] of KEYS) {
      const key = makeKey(root, mode)
      const dKey = demo.makeKey(root, mode)
      for (const notation of ['names', 'roman'] as const) {
        for (const input of ['', 'a', 'B', 'f#', 'F♯', 'd', '♭', 'v']) {
          expect(chips(key, notation, input)).toEqual(demo.chips(dKey, notation, input))
        }
      }
    }
  })
})

describe('golden parity: parsers (shared vocabulary)', () => {
  it('parseName agrees with the demo on the demo-parseable vocabulary', () => {
    const symbols = [
      'Am', 'F', 'C', 'G', 'Em', 'Dm', 'E', 'E7', 'A', 'D', 'Bdim', 'Bm7♭5', 'Bm7b5',
      'Am(add9)', 'Dsus2', 'Dsus4', 'Fadd9', 'B♭', 'Bb', 'B♭7', 'Cmaj7', 'Dm7', 'G7', 'Fm', 'Cm',
    ]
    for (const [root, mode] of [['A', 'minor'], ['C', 'major']] as const) {
      const key = makeKey(root, mode)
      const dKey = demo.makeKey(root, mode)
      for (const sym of symbols) {
        const ours = parseName(sym, key)
        const theirs = demo.parseName(sym, dKey)
        expect(theirs, `demo failed to parse ${sym}`).toBeTruthy()
        expect(ours, `we failed to parse ${sym}`).toBeTruthy()
        expect(core(ours!)).toEqual(core(theirs))
      }
    }
  })

  it('parseRoman agrees with the demo where the demo is correct (case-shadowed inputs excluded, §7.3)', () => {
    const romans = [
      'i', 'iv', 'v', '♭VI', 'bVI', '♭VII', '♭III', 'bIII', '♭II7', 'V/iv', 'V/♭III',
      'ii°', 'iiø7', 'ivsus2', 'i(add9)', 'v7', 'II', '♭V', 'iii7', 'VImaj7',
    ]
    // Case-shadowed inputs where the DEMO is wrong and our case-sensitive-first fix differs:
    // minor 'V'/'I'/'IV' (demo's ci first-match returns v/i/iv) and major 'iv' (demo
    // returns IV) — all pinned in parse.test.ts.
    const shadowed: Record<string, string[]> = { minor: ['V', 'I', 'IV'], major: ['iv'] }
    for (const [root, mode] of [['A', 'minor'], ['C', 'major']] as const) {
      const key = makeKey(root, mode)
      const dKey = demo.makeKey(root, mode)
      for (const r of romans.filter(x => !shadowed[mode]!.includes(x))) {
        const ours = parseRoman(r, key)
        const theirs = demo.parseRoman(r, dKey)
        expect(!!ours).toBe(!!theirs)
        if (ours && theirs) expect(core(ours)).toEqual(core(theirs))
      }
    }
  })
})
